
find_path(EPICS_CORE_INCLUDE_DIR ellLib.h
  PATHS ${EPICS_BASE} ENV EPICS_BASE
  PATH_SUFFIXES include
)
list(APPEND EPICS_INCLUDE_DIRS ${EPICS_CORE_INCLUDE_DIR})

find_path(EPICS_OS_INCLUDE_DIR osdSock.h
  PATHS ${EPICS_BASE_DIR}/include/os/${EPICS_OS}
)
list(APPEND EPICS_INCLUDE_DIR ${EPICS_OS_INCLUDE_DIR})

foreach(COMP IN LISTS EPICS_FIND_COMPONENTS ITEMS Com)
  find_library(EPICS_${COMP}_LIBRARY ${COMP}
    PATHS ${EPICS_BASE} ENV EPICS_BASE
    PATH_SUFFIXES lib/${EPICS_HOST_ARCH}
  )

  if(EPICS_${COMP}_LIBRARY)
    list(APPEND EPICS_LIBRARIES ${EPICS_${COMP}_LIBRARY})
    set(EPICS_${COMP}_FOUND TRUE)
  endif()
endforeach()

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(EPICS
  FOUND_VAR EPICS_FOUND
  REQUIRED_VARS EPICS_CORE_INCLUDE_DIR EPICS_OS_INCLUDE_DIR EPICS_LIBRARIES
  HANDLE_COMPONENTS
)
